### ISSUE TITLE
Followers running docker containers are not reconciled on restart.

### ISSUE THREAD

**Issue by nicktate** [containership/containership#123] opened 2016-06-29 16:21 UTC
- If you stop the containership process, don't delete the existing docker processes and restart the process after it has timeout connection with the cluster, when it comes back online it will not create new containers / reconcile the existing ones and the containers will be listed as "starting" in the web UI even though the old processes are still running

**Comment by normanjoyner** [comment] 2016-06-29 23:19
duplicate of containership/containership.core#54

**Closed** 2016-06-29 23:19 UTC
Labels: type/bug, type/duplicate
